#cloud-config
hostname: elk
manage_etc_hosts: true

package_update: true
package_upgrade: false

packages:
  - curl
  - jq
  - ca-certificates
  - nfs-common


runcmd:
  - mkdir -p /mnt/nas-elk
  - mountpoint -q /mnt/nas-elk || mount -t nfs -o vers=3,nolock,rw,hard,noatime 192.168.50.215:/volume1/shared/elk-snapshots /mnt/nas-elk || true
  - grep -q '/mnt/nas-elk' /etc/fstab || echo '192.168.50.215:/volume1/shared/elk-snapshots /mnt/nas-elk nfs vers=3,nolock,rw,hard,noatime,_netdev,x-systemd.automount 0 0' >> /etc/fstab
  - systemctl enable filebeat || true

final_message: "Cloud-init completed for elk"
