http:
  routers:
    registry:
      rule: Host(`registry.jclee.me`)
      entryPoints:
        - websecure
      service: registry
      middlewares:
        - rate-limit-relaxed@file
      tls:
        certResolver: cf
      priority: 10

    registry-http:
      rule: Host(`registry.jclee.me`)
      entryPoints:
        - web
      service: registry
      priority: 10

  services:
    registry:
      loadBalancer:
        servers:
          - url: http://192.168.50.215:5051
