#cloud-config
hostname: cliproxy
manage_etc_hosts: true

package_update: true
package_upgrade: false

packages:
  - curl
  - squid


runcmd:
  - systemctl enable squid || true

final_message: "Cloud-init completed for cliproxy"
