package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const (
	colorRed    = "\033[0;31m"
	colorGreen  = "\033[0;32m"
	colorYellow = "\033[1;33m"
	colorBold   = "\033[1m"
	colorNC     = "\033[0m"
)

func usage(program string) {
	fmt.Fprintf(os.Stderr, "Usage: %s [--save] [--check] [--help]\n", program)
	fmt.Fprintln(os.Stderr, "  --save   Write credentials to .env.local for reuse")
	fmt.Fprintln(os.Stderr, "  --check  Validate credentials without printing export commands")
	fmt.Fprintln(os.Stderr, "  --help   Show this help")
}

func main() {
	var save bool
	var checkOnly bool
	var help bool

	flagSet := flag.NewFlagSet(os.Args[0], flag.ContinueOnError)
	flagSet.SetOutput(os.Stderr)
	flagSet.BoolVar(&save, "save", false, "Write credentials to .env.local for reuse")
	flagSet.BoolVar(&checkOnly, "check", false, "Validate credentials without printing export commands")
	flagSet.BoolVar(&help, "help", false, "Show help")
	flagSet.BoolVar(&help, "h", false, "Show help")

	args := os.Args[1:]
	if len(args) > 0 && args[0] == "--" {
		args = args[1:]
	}

	if err := flagSet.Parse(args); err != nil {
		usage(filepath.Base(os.Args[0]))
		os.Exit(2)
	}
	if help {
		usage(filepath.Base(os.Args[0]))
		os.Exit(0)
	}

	if _, err := exec.LookPath("op"); err != nil {
		fmt.Fprintf(os.Stderr, "%sError: op CLI not installed%s\n", colorRed, colorNC)
		fmt.Fprintln(os.Stderr, "Install: https://developer.1password.com/docs/cli/get-started/")
		os.Exit(1)
	}

	repoRoot := resolveRepoRoot()
	token := strings.TrimSpace(os.Getenv("OP_SERVICE_ACCOUNT_TOKEN"))
	if token == "" {
		tokenFromFile, loaded := loadTokenFromEnvLocal(filepath.Join(repoRoot, ".env.local"))
		if loaded {
			fmt.Fprintf(os.Stderr, "%sLoading credentials from .env.local...%s\n", colorYellow, colorNC)
			token = tokenFromFile
		}
	}

	if token == "" {
		fmt.Fprintf(os.Stderr, "%sError: OP_SERVICE_ACCOUNT_TOKEN not set%s\n", colorRed, colorNC)
		fmt.Fprintln(os.Stderr)
		fmt.Fprintln(os.Stderr, "Get your service account token from 1Password admin console:")
		fmt.Fprintln(os.Stderr, "  https://my.1password.com -> Settings -> Service Accounts")
		fmt.Fprintln(os.Stderr)
		fmt.Fprintln(os.Stderr, "Then set it:")
		fmt.Fprintln(os.Stderr, "  export OP_SERVICE_ACCOUNT_TOKEN='ops_...'")
		fmt.Fprintln(os.Stderr)
		fmt.Fprintln(os.Stderr, "Or create .env.local at the repo root:")
		fmt.Fprintln(os.Stderr, "  echo 'OP_SERVICE_ACCOUNT_TOKEN=ops_...' > .env.local")
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "%sValidating 1Password credentials...%s\n", colorBold, colorNC)
	cmd := exec.Command("op", "whoami")
	cmd.Env = buildWhoamiEnv(token)
	if _, err := cmd.CombinedOutput(); err != nil {
		fmt.Fprintf(os.Stderr, "%s  [!!] 1Password authentication failed%s\n", colorRed, colorNC)
		fmt.Fprintln(os.Stderr, "  Check your OP_SERVICE_ACCOUNT_TOKEN value")
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "%s  [OK]%s 1Password authenticated\n", colorGreen, colorNC)

	if checkOnly {
		fmt.Fprintf(os.Stderr, "\n%s%sAll credentials valid.%s\n", colorGreen, colorBold, colorNC)
		fmt.Fprintln(os.Stderr, "  OP_SERVICE_ACCOUNT_TOKEN: set")
		os.Exit(0)
	}

	if save {
		envFile := filepath.Join(repoRoot, ".env.local")
		content := fmt.Sprintf("# Auto-generated by scripts/setup-local-env.go (%s)\n# Gitignored via **/.env.* pattern - NEVER commit this file.\nOP_SERVICE_ACCOUNT_TOKEN=%s\nTF_VAR_op_service_account_token=%s\n", time.Now().Format(time.RFC3339), token, token)
		if err := os.WriteFile(envFile, []byte(content), 0o600); err != nil {
			fmt.Fprintf(os.Stderr, "%sError: failed writing .env.local: %v%s\n", colorRed, err, colorNC)
			os.Exit(1)
		}
		if err := os.Chmod(envFile, 0o600); err != nil {
			fmt.Fprintf(os.Stderr, "%sError: failed setting .env.local mode: %v%s\n", colorRed, err, colorNC)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "%s  [OK]%s Credentials saved to .env.local (mode 600)\n", colorGreen, colorNC)
	}

	fmt.Fprintf(os.Stderr, "%s  [OK]%s OP_SERVICE_ACCOUNT_TOKEN present\n", colorGreen, colorNC)
	fmt.Fprintf(os.Stderr, "%s  [OK]%s TF_VAR_op_service_account_token prepared\n", colorGreen, colorNC)
	fmt.Fprintf(os.Stderr, "\n%s%sLocal credentials configured.%s\n", colorGreen, colorBold, colorNC)
	fmt.Fprintln(os.Stderr, "Run Terraform:")
	fmt.Fprintln(os.Stderr, "  make plan SVC=pve")
	fmt.Fprintln(os.Stderr, "  make plan SVC=cloudflare")
	fmt.Fprintln(os.Stderr)
	if !save {
		fmt.Fprintf(os.Stderr, "%sTip:%s Credentials are session-only. To persist:\n", colorYellow, colorNC)
		fmt.Fprintln(os.Stderr, "  eval \"$(go run scripts/setup-local-env.go -- --save)\"")
	}

	fmt.Printf("export TF_VAR_op_service_account_token=%s\n", shellQuote(token))
	fmt.Println("unset OP_CONNECT_HOST")
	fmt.Println("unset OP_CONNECT_TOKEN")
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}

func resolveRepoRoot() string {
	wd, err := os.Getwd()
	if err != nil {
		return "."
	}
	current := wd
	for {
		candidate := filepath.Join(current, "scripts", "setup-local-env.go")
		if _, statErr := os.Stat(candidate); statErr == nil {
			return current
		}
		parent := filepath.Dir(current)
		if parent == current {
			return wd
		}
		current = parent
	}
}

func loadTokenFromEnvLocal(path string) (string, bool) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}

	lines := strings.Split(string(content), "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		trimmed = strings.TrimPrefix(trimmed, "export ")
		parts := strings.SplitN(trimmed, "=", 2)
		if len(parts) != 2 {
			continue
		}
		if strings.TrimSpace(parts[0]) != "OP_SERVICE_ACCOUNT_TOKEN" {
			continue
		}
		value := strings.TrimSpace(parts[1])
		if len(value) >= 2 {
			if (strings.HasPrefix(value, "\"") && strings.HasSuffix(value, "\"")) || (strings.HasPrefix(value, "'") && strings.HasSuffix(value, "'")) {
				value = value[1 : len(value)-1]
			}
		}
		if value != "" {
			return value, true
		}
	}

	return "", false
}

func buildWhoamiEnv(token string) []string {
	env := make([]string, 0, len(os.Environ())+1)
	for _, entry := range os.Environ() {
		if strings.HasPrefix(entry, "OP_CONNECT_HOST=") || strings.HasPrefix(entry, "OP_CONNECT_TOKEN=") {
			continue
		}
		env = append(env, entry)
	}
	env = append(env, "OP_SERVICE_ACCOUNT_TOKEN="+token)
	return env
}
