#!/usr/bin/env bash
# scripts/setup-local-env.sh — Bootstrap local Terraform credentials from 1Password
#
# Validates 1Password connectivity and exports OP_SERVICE_ACCOUNT_TOKEN
# for the Terraform 1Password provider.
#
# Usage:
#   source scripts/setup-local-env.sh          # Load into current shell
#   source scripts/setup-local-env.sh --save   # Load + write .env.local for reuse
#   source scripts/setup-local-env.sh --check  # Validate without exporting
#
# Prerequisites:
#   - op CLI v2+ installed (https://developer.1password.com/docs/cli/get-started/)
#   - OP_SERVICE_ACCOUNT_TOKEN set (from 1Password admin → Service Accounts)
#
# Credential layers loaded:
#   Layer 1 — 1Password TF:    OP_SERVICE_ACCOUNT_TOKEN (already in env)
#   Layer 2 — Proxmox:         Already in terraform.tfvars (no action needed)

# --- Colors ---
_RED='\033[0;31m'
_GREEN='\033[0;32m'
_YELLOW='\033[1;33m'
_BOLD='\033[1m'
_NC='\033[0m'

# --- Parse args ---
_SAVE=false
_CHECK_ONLY=false
for _arg in "$@"; do
  case "$_arg" in
    --save)  _SAVE=true ;;
    --check) _CHECK_ONLY=true ;;
    -h|--help)
      printf "Usage: source %s [--save|--check]\n" "${BASH_SOURCE[0]:-$0}"
      printf "  --save   Write credentials to .env.local for reuse\n"
      printf "  --check  Validate credentials without exporting\n"
      return 0 2>/dev/null || exit 0
      ;;
  esac
done

# --- Dependency: op CLI ---
if ! command -v op >/dev/null 2>&1; then
  printf "${_RED}Error: op CLI not installed${_NC}\n" >&2
  printf "Install: https://developer.1password.com/docs/cli/get-started/\n" >&2
  return 1 2>/dev/null || exit 1
fi

# --- Dependency: OP_SERVICE_ACCOUNT_TOKEN ---
if [[ -z "${OP_SERVICE_ACCOUNT_TOKEN:-}" ]]; then
  # Try loading from .env.local if it exists
  _ENV_LOCAL="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)/.env.local"
  if [[ -f "$_ENV_LOCAL" ]]; then
    printf "${_YELLOW}Loading credentials from .env.local...${_NC}\n"
    set -a
    # shellcheck disable=SC1090
    source "$_ENV_LOCAL"
    set +a
  fi

  if [[ -z "${OP_SERVICE_ACCOUNT_TOKEN:-}" ]]; then
    printf "${_RED}Error: OP_SERVICE_ACCOUNT_TOKEN not set${_NC}\n" >&2
    printf "\n" >&2
    printf "Get your service account token from 1Password admin console:\n" >&2
    printf "  https://my.1password.com → Settings → Service Accounts\n" >&2
    printf "\n" >&2
    printf "Then set it:\n" >&2
    printf "  export OP_SERVICE_ACCOUNT_TOKEN='ops_...'\n" >&2
    printf "\n" >&2
    printf "Or create .env.local at the repo root:\n" >&2
    printf "  echo 'OP_SERVICE_ACCOUNT_TOKEN=ops_...' > .env.local\n" >&2
    return 1 2>/dev/null || exit 1
  fi
fi

# --- Validate 1Password connectivity ---
printf "${_BOLD}Validating 1Password credentials...${_NC}\n"

if ! op whoami &>/dev/null; then
  printf "${_RED}  [!!] 1Password authentication failed${_NC}\n" >&2
  printf "  Check your OP_SERVICE_ACCOUNT_TOKEN value\n" >&2
  return 1 2>/dev/null || exit 1
fi
printf "${_GREEN}  [OK]${_NC} 1Password authenticated\n"

# --- Check-only mode: report status and exit ---
if $_CHECK_ONLY; then
  printf "\n${_GREEN}${_BOLD}All credentials valid.${_NC}\n"
  printf "  OP_SERVICE_ACCOUNT_TOKEN: set\n"
  return 0 2>/dev/null || exit 0
fi

# --- Export credentials ---
# OP_SERVICE_ACCOUNT_TOKEN already exported (checked above)
printf "${_GREEN}  [OK]${_NC} OP_SERVICE_ACCOUNT_TOKEN present\n"

# --- Optionally save to .env.local ---
if $_SAVE; then
  _REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
  _ENV_FILE="${_REPO_ROOT}/.env.local"

  cat > "$_ENV_FILE" <<EOF
# Auto-generated by scripts/setup-local-env.sh ($(date -Iseconds))
# Gitignored via **/.env.* pattern — NEVER commit this file.
OP_SERVICE_ACCOUNT_TOKEN=${OP_SERVICE_ACCOUNT_TOKEN}
EOF
  chmod 600 "$_ENV_FILE"
  printf "${_GREEN}  [OK]${_NC} Credentials saved to .env.local (mode 600)\n"
fi

# --- Summary ---
printf "\n${_GREEN}${_BOLD}Local credentials configured.${_NC}\n"
printf "Run Terraform:\n"
printf "  make plan SVC=pve\n"
printf "  make plan SVC=cloudflare\n"
printf "\n"

if ! $_SAVE; then
  printf "${_YELLOW}Tip:${_NC} Credentials are session-only. To persist:\n"
  printf "  source scripts/setup-local-env.sh --save\n"
fi

# --- Cleanup script-local vars ---
unset _RED _GREEN _YELLOW _BOLD _NC _SAVE _CHECK_ONLY _arg
unset _ENV_LOCAL _REPO_ROOT _ENV_FILE
