terraform {
  required_version = ">= 1.7, < 2.0"

  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "~> 0.94"
    }
  }
}

data "proxmox_virtual_environment_nodes" "nodes" {}

resource "proxmox_virtual_environment_container" "this" {
  node_name    = var.node_name
  vm_id        = var.vmid
  description  = var.description
  started      = true
  unprivileged = var.privileged ? false : true

  initialization {
    hostname = var.hostname

    ip_config {
      ipv4 {
        address = "${var.ip_address}/24"
        gateway = var.network_gateway
      }
    }

    dns {
      servers = var.dns_servers
    }

    dynamic "user_account" {
      for_each = length(var.ssh_public_keys) > 0 ? [1] : []
      content {
        keys = var.ssh_public_keys
      }
    }
  }

  memory {
    dedicated = var.memory
    swap      = var.swap
  }

  cpu {
    cores = var.cores
  }

  disk {
    datastore_id = var.datastore_id
    size         = var.disk_size
  }

  network_interface {
    name   = "eth0"
    bridge = "vmbr0"
  }

  features {
    nesting = true
  }

  operating_system {
    template_file_id = var.template_file_id
    type             = "debian"
  }
  dynamic "mount_point" {
    for_each = var.mount_points
    content {
      volume = mount_point.value.volume
      path   = mount_point.value.path
    }
  }


  # =============================================================================
  # LIFECYCLE MANAGEMENT
  # =============================================================================

  lifecycle {
    # Preconditions: Verify environment before creation/update
    precondition {
      condition     = contains(data.proxmox_virtual_environment_nodes.nodes.names, var.node_name)
      error_message = <<-EOT
        Node '${var.node_name}' not found in Proxmox cluster.
        Available nodes: ${join(", ", data.proxmox_virtual_environment_nodes.nodes.names)}
        Fix: Verify node is online or update var.node_name
      EOT
    }

    precondition {
      condition     = var.vmid >= var.managed_vmid_min && var.vmid <= var.managed_vmid_max
      error_message = <<-EOT
        Container '${var.hostname}' VMID ${var.vmid} is outside managed range.
        Allowed: ${var.managed_vmid_min}-${var.managed_vmid_max}
        Current: ${var.vmid}
        Fix: Update VMID in container definition for '${var.hostname}'
      EOT
    }

    precondition {
      condition     = var.memory >= 256 && var.memory % 256 == 0
      error_message = <<-EOT
        Container '${var.hostname}' memory configuration invalid.
        Current: ${var.memory}MB
        Requirements: >= 256MB and divisible by 256
        Fix: Set memory to 256, 512, 1024, 2048, etc.
      EOT
    }

    # Postconditions: Verify successful deployment
    postcondition {
      condition     = self.started == true
      error_message = <<-EOT
        Container '${var.hostname}' (VMID ${var.vmid}) failed to start after deployment.
        Node: ${self.node_name}
        Status: stopped
        Fix: Check Proxmox logs with: pct status ${var.vmid}
      EOT
    }

    postcondition {
      condition     = self.vm_id == null || self.vm_id == var.vmid
      error_message = "Container '${var.hostname}' VMID mismatch detected. Expected: ${var.vmid}, Actual: ${coalesce(self.vm_id, "null")}"
    }

    # Ignore changes: ONLY for auto-generated or non-critical fields
    # REDUCED from original - now only MAC address and truly read-only fields
    ignore_changes = [
      network_interface[0].mac_address,
      operating_system,
      template,
      startup,
      disk[0].datastore_id,
      mount_point,
    ]

    # KEPT in ignore_changes (auto-generated or read-only fields):
    # - mac_address           → Auto-generated by Proxmox, changes cause unnecessary recreate
    # - operating_system      → Read-only field populated by Proxmox, not user-settable
    # - template              → Read-only field, set at creation time only
    # - startup               → Can be manually adjusted via PVE UI for maintenance
    # - disk[0].datastore_id  → Storage moves handled outside TF (ZFS operations)
    # - mount_point           → Bind mounts managed outside TF lifecycle
    #
    # NOT ignored (Terraform WILL detect drift on these):
    # - disk[0].size          → Disk resize must be tracked
    # - cpu[0].cores          → Resource changes must be tracked
    # - memory[0].swap        → Resource changes must be tracked
    # - features              → Feature flags (nesting, etc.) are critical
    # - console               → Console configuration matters
    # - network_interface[0].firewall → Security settings must be tracked

    prevent_destroy = true
  }
}
