name: Branch Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    uses: ./.github/workflows/_branch-cleanup.yml
    secrets: inherit  # pragma: allowlist secret
