name: Cloudflare Plan

on:
  pull_request:
    paths:
      - "300-cloudflare/**"

concurrency:
  group: cloudflare-plan-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    uses: ./.github/workflows/_terraform-plan.yml
    with:
      service-name: Cloudflare
      working-directory: 300-cloudflare
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.TF_VAR_CLOUDFLARE_ACCOUNT_ID }}
      TF_VAR_CLOUDFLARE_ZONE_ID: ${{ secrets.TF_VAR_CLOUDFLARE_ZONE_ID }}
      TF_VAR_SYNOLOGY_DOMAIN: ${{ secrets.TF_VAR_SYNOLOGY_DOMAIN }}
      TF_VAR_ACCESS_ALLOWED_EMAILS: ${{ secrets.TF_VAR_ACCESS_ALLOWED_EMAILS }}
      TF_VAR_GITHUB_TOKEN: ${{ secrets.TF_VAR_GITHUB_TOKEN }}
      OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
      OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
