name: Cloudflare Plan

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '300-cloudflare/**'

concurrency:
  group: cloudflare-plan-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    uses: ./.github/workflows/_terraform-plan.yml
    with:
      service-name: Cloudflare
      working-directory: 300-cloudflare
    secrets: inherit  # pragma: allowlist secret
