name: ELK Health Check

on:
  workflow_run:
    workflows:
      - "ELK Apply"
    types: [completed]
    branches: [master]
  push:
    branches: [master]
    paths:
      - "105-elk/**"
      - ".github/workflows/elk-health-check.yml"
      - ".github/workflows/_elk-health-check.yml"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

concurrency:
  group: elk-health-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  health-check:
    uses: ./.github/workflows/_elk-health-check.yml
    secrets: inherit  # pragma: allowlist secret
