name: Grafana Plan

on:
  pull_request:
    paths:
      - "104-grafana/terraform/**"
      - "104-grafana/dashboards/**"

concurrency:
  group: grafana-plan-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    uses: ./.github/workflows/_terraform-plan.yml
    with:
      service-name: Grafana
      working-directory: 104-grafana/terraform
      needs-infra-state: true
    secrets: inherit # pragma: allowlist secret
