name: Secret Audit

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

permissions:
  contents: read
  issues: write

jobs:
  audit:
    uses: ./.github/workflows/_secret-audit.yml
    secrets: inherit
