name: Slack Plan

on:
  pull_request:
    paths:
      - "320-slack/**"

concurrency:
  group: slack-plan-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    uses: ./.github/workflows/_terraform-plan.yml
    with:
      service-name: Slack
      working-directory: 320-slack
    secrets: inherit # pragma: allowlist secret
