name: 'Stale issue/PR cleanup'

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    uses: ./.github/workflows/_stale.yml
    secrets: inherit  # pragma: allowlist secret
