name: Terraform Test

on:
  pull_request:
    paths:
      - "modules/**"
      - "tests/**"
      - "100-pve/variables.tf"
      - "300-cloudflare/variables.tf"
      - "320-slack/variables.tf"
      - "104-grafana/terraform/variables.tf"
      - "105-elk/terraform/variables.tf"
  push:
    branches: [master]
    paths:
      - "modules/**"
      - "tests/**"
      - "100-pve/variables.tf"
      - "300-cloudflare/variables.tf"
      - "320-slack/variables.tf"
      - "104-grafana/terraform/variables.tf"
      - "105-elk/terraform/variables.tf"
  workflow_dispatch:

concurrency:
  group: terraform-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/_terraform-test.yml
    secrets: inherit  # pragma: allowlist secret
