name: Terraform Docs

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "modules/**"
      - ".github/workflows/terraform-docs.yml"
      - ".github/workflows/_terraform-docs.yml"

permissions:
  contents: write

concurrency:
  group: terraform-docs-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  docs:
    uses: ./.github/workflows/_terraform-docs.yml
    secrets: inherit  # pragma: allowlist secret
