name: Deploy Synology Proxy Worker

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "300-cloudflare/workers/synology-proxy/**"

permissions:
  contents: read
  issues: write

jobs:
  deploy:
    uses: ./.github/workflows/_worker-deploy.yml
    with:
      working-directory: 300-cloudflare/workers/synology-proxy
      worker-name: synology-proxy
    secrets: inherit  # pragma: allowlist secret
